name: Build and Release Clients

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build Android Client
      run: |
        cd demo_src/TCP_Client/MobileIMSDK4aDemo_tcp
        ./gradlew build
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

    - name: Build Java Client
      run: |
        cd demo_src/TCP_Client/MobileIMSDK4jDemo_tcp
        ./gradlew build
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

    - name: Build iOS Client
      run: |
        cd demo_src/TCP_Client/MobileIMSDK4iDemo_tcp
        xcodebuild -scheme MobileIMSDK4iDemo_tcp -sdk iphoneos
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

    - name: Upload Release Assets
      uses: actions/upload-artifact@v3
      with:
        name: TCP_Client_Builds
        path: |
          demo_src/TCP_Client/MobileIMSDK4aDemo_tcp/build/outputs/**/*.apk
          demo_src/TCP_Client/MobileIMSDK4jDemo_tcp/build/libs/*.jar
          demo_src/TCP_Client/MobileIMSDK4iDemo_tcp/build/Release-iphoneos/*.app

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Release Assets
      uses: actions/download-artifact@v3
      with:
        name: TCP_Client_Builds
        path: release-assets

    - name: Create GitHub Release
      uses: actions/create-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Release of TCP Clients
        draft: false
        prerelease: false
        files: |
          release-assets/**/*.*
